language: python
python:
  - 3.5
  - 3.6
install:
  - pip install -q -r requirements.txt
  - pip install -q -r docs/requirements.txt
  - pip install -q yapf==0.27
  - pip install -q pylint==2.3.1
script:
  - yapf --diff --recursive notif/
  - pylint notif/
  - cd docs
  - ./rebuild_html_doc.sh
  - cd ..
deploy:
  target-branch: gh-pages
  github_token: "$GITHUB_TOKEN"
  skip-cleanup: true
  local-dir: "./docs/_build/html/"
  provider: pages
  on:
    branch: master
